### ISSUE TITLE
manipulate can be activated many times and seem to overlay

### ISSUE THREAD

**Issue by mirlip** [s-leger/blenderPolygons#5]
When clicking manipulate many times, the handles, numbers, etc. becomes darker. Shouldn't it be a toggle = second click deactivate manipulate handles on the active object?

**Comment by s-leger** [comment]
Hi, 
Thank you for reporting !

Currently there is no control on manipulate mode / toggle, so when clicking many times you enable multiple handles.

Right click to get out of manipulate mode.

As for a enable/disable mode for manipulators, currently it is unclear whenever i must allow multiple objects manipulators and how to handle it, since you could end up with many objects with manipulators enabled and in the end find you to select and disable every one by hand.
 
As a side note: why the hell are you spamming manipulate button ?

**Comment by mirlip** [comment]
Hi,
I clicked a second time because I thought it was the way to disable it. It is great to have manipulators on many objects, but only one per object. If the user click manipulate on an object which already has manipulators, I think it should deactivate them on this one or on the whole selection.

**Comment by s-leger** [comment]
Ok, now i understand, does make sense.
Si implemented a toggle for manipulator button click.

**Comment by s-leger** [comment]
Fixed in source, will be part of 1.2 series release.

**Comment by mirlip** [comment]
thanks for the fix. There is a convention in Blender. When you modify a value, it only modifies the active object by default. If alt is pressed while confirming, it applies the modification to the whole selection. Is it possible to follow that behavior for the manipulate switch?

**Comment by s-leger** [comment]
Seem possible, will give a try.

**Comment by mirlip** [comment]
It becomes a real pleasure to work with this addon. The UI back in viewport like 2.8 wanted is already there and the consistence with Blender makes it feel very integrated, muscle memory really helps a lot :)

**Comment by s-leger** [comment]
alt to modify many values at once is part of native property panel. 
While recent changes done make addon panels working in property panel (object), seem it's not intended use for core's dev, so i've to keep carefull about this.
So i'm bit stuck in 3d view, wich also make sense as when in full screen you'll have access to properties.
In the between use "copy to selected" to share params between selected objects.
